root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended # eslint推奨ルール
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - "@nuxtjs/eslint-config-typescript"
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: "@typescript-eslint/parser"
  extraFileExtensions:
    - ".vue"
plugins:
  - "@typescript-eslint"
  - vue
rules: { "vue/multi-word-component-names": "off" }
